app = "crypto-ai-bot"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile.simple"

[env]
  BACKEND_PORT = "8000"
  ENABLE_DOCS = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/ping"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 