[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthcheck-railway"
healthcheckTimeout = 1800
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "crypto-ai-bot"
port = 8000 