[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

# Forzar nuevo deploy
# Railway healthcheck test

[[services]]
name = "crypto-ai-bot"
port = 8000 