[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "crypto-ai-bot"
port = 8000 