[build]
builder = "dockerfile"

[deploy]
startCommand = "sh scripts/railway-start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "crypto-ai-bot"
port = 8000 