services:
  - type: web
    name: crypto-ai-bot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      echo "🔨 Iniciando build en Render..."
      pip install --upgrade pip
      pip install -r requirements/common.txt
      echo "✅ Dependencias Python instaladas"
    startCommand: |
      echo "🚀 Iniciando backend..."
      cd src/backend
      python main_secure.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: BACKEND_PORT
        value: 8000
      - key: ENABLE_DOCS
        value: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /ping
    autoDeploy: true
    numInstances: 1 