services:
  - type: web
    name: crypto-ai-bot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      echo "🔨 Iniciando build en Render..."
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "✅ Dependencias Python instaladas"
    startCommand: |
      echo "🚀 Iniciando backend..."
      cd src/backend
      python main_secure.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: BACKEND_PORT
        value: 8000
      - key: ENABLE_DOCS
        value: false
      - key: ENVIRONMENT
        value: production
      - key: BACKEND_ALLOWED_ORIGINS
        value: https://crypto-ai-bot-backend.onrender.com,http://localhost:3000
      - key: BACKEND_ALLOWED_HOSTS
        value: crypto-ai-bot-backend.onrender.com,localhost,127.0.0.1
      - key: BACKEND_RATE_LIMIT_PER_MINUTE
        value: 60
      - key: BACKEND_RATE_LIMIT_PER_HOUR
        value: 1000
      - key: BACKEND_RATE_LIMIT_PER_DAY
        value: 10000
    healthCheckPath: /ping
    autoDeploy: true
    numInstances: 1 